[package]
name = "rocket"
version = "0.1.0"
authors = ["Rousan Ali <rousanali786@gmail.com>"]
edition = "2018"

[dependencies]
# rocket = "0.4.3"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "async" }